#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get current node version
current_version=$(node -v)
# Get required version from .nvmrc (with v prefix removed)
required_version="v$(cat .nvmrc)"

if [ "$current_version" != "$required_version" ]; then
  echo "⚠️  Wrong Node.js version! Required: $required_version, Current: $current_version"
  echo "Run 'nvm use' to switch to the correct version"
  exit 1
fi
